//база данных  в виде массива

export const bdGoods = [
  {
    name: "superSocks1",
    price: 6,
    size:"XL",
    color:"red",
    manufacturer:"Беларусь",
    srcImg: "./images/socks1.png",
    description: "Первоклассные носки из Беларуси",
    rating: 0,
    comments: "",
    id:1,
    category:"socks",

  },{
    name: "Socks1",
    price: 12.3,
    size:"XXL",
    color:"blue",
    manufacturer:"Россия",
    srcImg: "./images/socks2.png",
    description: "Первоклассные носки из России",
    rating: 0,
    comments: "",
    id:2,
    category:"socks",
  },{
    name: "superSocks2",
    price: 3.5,
    size:"M",
    color:"red",
    manufacturer:"Беларусь",
    srcImg: "./images/socks3.png",
    description: "Суперские носки ",
    rating: 0,
    comments: "",
    id:3,
    category:"socks",
  },{
    name: "superSocks3",
    price: 13,
    size:"XL",
    color:"black",
    manufacturer:"Беларусь",
    srcImg: "./images/socks4.png",
    description: "Первоклассные носки из Беларуси",
    rating: 0,
    comments: "",
    id:4,
    category:"socks",
  },{
    name: "Socks1",
    price: 11,
    size:"XL",
    color:"white",
    manufacturer:"Россия",
    srcImg: "./images/socks5.png",
    description: "Первоклассные носки из России",
    rating: 0,
    comments: "",
    id:5,
    category:"socks",
  },{
    name: "superSocks17",
    price: 100500,
    size:"XL",
    color:"red",
    manufacturer:"Беларусь",
    srcImg: "./images/socks6.png",
    description: "Первоклассные носки из Беларуси",
    rating: 0,
    comments: "",
    id:6,
    category:"socks",
  },{
    name: "superSocks23",
    price: 15,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/socks7.png",
    description: "Первоклассные носки из Англии",
    rating: 0,
    comments: "",
    id:7,
    category:"socks",
  },{
    name: "superGloves",
    price: 15,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/gloves1.jpg",
    description: "Первоклассные перчатки из Англии",
    rating: 0,
    comments: "",
    id:8,
    category: "gloves",
  },{
    name: "superSocks23",
    price: 15,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/gloves2.jpg",
    description: "Первоклассные перчатки из Англии",
    rating: 0,
    comments: "",
    id:9,
    category: "gloves",
  },{
    name: "superGloves23",
    price: 15,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/gloves3.jpeg",
    description: "Первоклассные перчатки из Англии",
    rating: 0,
    comments: "",
    id:10,
    category: "gloves",
  },{
    name: "Gloves323",
    price: 125,
    size:"XL",
    color:"black",
    manufacturer:"Англия",
    srcImg: "./images/gloves4.jpg",
    description: "Первоклассные перчатки из Англии",
    rating: 0,
    comments: "",
    id:11,
    category: "gloves",
  },{
    name: "Gloves",
    price: 5,
    size:"XL",
    color:"blue",
    manufacturer:"Англия",
    srcImg: "./images/gloves5.jpg",
    description: "Первоклассные перчатки из Англии",
    rating: 0,
    comments: "",
    id:12,
    category: "gloves",
  },{
    name: "superGloves",
    price: 2125,
    size:"XL",
    color:"black",
    manufacturer:"Англия",
    srcImg: "./images/gloves6.jpg",
    description: "Первоклассные перчатки из Англии",
    rating: 0,
    comments: "",
    id:13,
    category: "gloves",
  },{
    name: "superHat23",
    price: 11235,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/hat1.jpg",
    description: "Первоклассные шляпы из Англии",
    rating: 0,
    comments: "",
    id:14,
    category: "hats"
  },{
    name: "superHat23",
    price: 1565,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/hat2.jpg",
    description: "Первоклассные шляпы из Англии",
    rating: 0,
    comments: "",
    id:15,
    category: "hats"
  },{
    name: "Hat23",
    price: 15,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/hat3.jpg",
    description: "Первоклассные шляпы из Англии",
    rating: 0,
    comments: "",
    id:16,
    category: "hats"
  },{
    name: "SuperHat123",
    price: 25,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/hat4.jpg",
    description: "Первоклассные шляпы из Англии",
    rating: 0,
    comments: "",
    id:17,
    category: "hats"
  },{
    name: "Hat23",
    price: 29,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/hat5.jpg",
    description: "Первоклассные шляпы из Англии",
    rating: 0,
    comments: "",
    id:18,
    category: "hats"
  },{
    name: "GoodHat",
    price: 118,
    size:"XL",
    color:"red",
    manufacturer:"Англия",
    srcImg: "./images/hat6.jpg",
    description: "Первоклассные шляпы из Англии",
    rating: 0,
    comments: "",
    id:19,
    category: "hats"
  }];
